// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcoBNaVszdpesk7EKdE3hQRl3wlw-20PE',
    appId: '1:571398103298:web:24d0d909fd90e8a7e0221b',
    messagingSenderId: '571398103298',
    projectId: 'tccds20232s',
    authDomain: 'tccds20232s.firebaseapp.com',
    storageBucket: 'tccds20232s.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLx2QnmRRF5pb9kwF_D6GAfh3YTME4qY',
    appId: '1:571398103298:android:36145b3540131186e0221b',
    messagingSenderId: '571398103298',
    projectId: 'tccds20232s',
    storageBucket: 'tccds20232s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQs4SIEfP9tvgTYwPAJL0RgTDTyHfui90',
    appId: '1:571398103298:ios:04ea3651b096da18e0221b',
    messagingSenderId: '571398103298',
    projectId: 'tccds20232s',
    storageBucket: 'tccds20232s.appspot.com',
    iosClientId: '571398103298-ipmjn27lq796urd37jar26940d54hn4v.apps.googleusercontent.com',
    iosBundleId: 'br.com.etec.dtccds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQs4SIEfP9tvgTYwPAJL0RgTDTyHfui90',
    appId: '1:571398103298:ios:04ea3651b096da18e0221b',
    messagingSenderId: '571398103298',
    projectId: 'tccds20232s',
    storageBucket: 'tccds20232s.appspot.com',
    iosClientId: '571398103298-ipmjn27lq796urd37jar26940d54hn4v.apps.googleusercontent.com',
    iosBundleId: 'br.com.etec.dtccds',
  );
}
